Numpy : Practice Problem

1. Extract all odd numbers from arr


In [14]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

2. Replace all odd numbers in arr with -1

In [19]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]= -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

3. Convert a 1D array to a 2D array with 2 rows

In [21]:
arr=np.arange(10)
np.reshape(arr,(2,5))


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

4. Stack arrays a and b vertically

In [22]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

5. Get all items between 5 and 10 from a

In [70]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>5) & (a<11)]

array([ 6,  9, 10])

Desired Output:
(array([6, 9, 10]),)

6. Create a null vector of size 10 but the fifth value which is 1.

In [31]:
a = np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Create a vector with values ranging from 10 to 49.

In [32]:
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

8. Create a 10x10 array with random values and find the minimum and maximum values.

In [41]:
a = np.random.random((10,10))
a

array([[0.66694187, 0.24245736, 0.45116188, 0.06362101, 0.19250774,
        0.37338286, 0.21296635, 0.38069161, 0.408066  , 0.93448498],
       [0.75908043, 0.15113891, 0.3240775 , 0.08051131, 0.36855399,
        0.96745469, 0.23608813, 0.74382633, 0.29584966, 0.70639331],
       [0.36279765, 0.15151464, 0.15561728, 0.32101377, 0.6682208 ,
        0.79244342, 0.45332162, 0.1598382 , 0.82756361, 0.92777037],
       [0.53627292, 0.23545727, 0.12992085, 0.91096473, 0.4283954 ,
        0.78030655, 0.1293123 , 0.51773753, 0.02759031, 0.78309526],
       [0.872136  , 0.81763354, 0.18341702, 0.45997407, 0.21962814,
        0.4312079 , 0.30755372, 0.43403413, 0.76887109, 0.72169037],
       [0.76222945, 0.52569969, 0.86179251, 0.42982078, 0.25034682,
        0.18109899, 0.3728292 , 0.23852254, 0.72136326, 0.98938832],
       [0.64045932, 0.86888871, 0.17790614, 0.80241302, 0.51662245,
        0.06869955, 0.64420779, 0.32311951, 0.98298756, 0.64684745],
       [0.00126257, 0.20617559, 0.7526934

In [42]:
a.min()

0.0012625697730151986

In [43]:
a.max()

0.9893883202924121

9. Create a 3*3 matrix and print it's transpose matrix

In [45]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

10. Create two arrays of 2-D and find dot product of it.

In [47]:
a = np.array([[3,4],[4,3]])
b = np.array([[4,3],[3,4]])
np.dot(a,b)

array([[24, 25],
       [25, 24]])

11. Compute the maximum for each row in the given array.

In [48]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a

array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

In [49]:
np.max(a,axis = 0)

array([9, 9, 9])

12. Select 3rd & 5th row and 3rd & 4th columns

In [53]:
data = np.random.randint(10,100,(5,4))
data

array([[13, 94, 89, 20],
       [97, 70, 13, 58],
       [62, 53, 46, 15],
       [81, 48, 96, 52],
       [94, 86, 43, 68]])

In [56]:
data[[2,4],2:4]

array([[46, 15],
       [43, 68]])

13. Convert below matrix into vector

In [58]:
matrix = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

14. The product of two inverse matrix is identical matrix,prove

In [64]:
# create a square matrix
m = np.array([[2,3],
              [2,4]])
n = np.linalg.inv(m)
np.dot(m,n)

array([[1., 0.],
       [0., 1.]])

15. Create a matrix from a uniform distribution over [0, 1)

In [67]:
a = np.random.rand(4,4)
a

array([[0.52695039, 0.42710838, 0.98263043, 0.14045149],
       [0.7484116 , 0.78884039, 0.73039662, 0.84561834],
       [0.55619038, 0.05686271, 0.88672457, 0.31441695],
       [0.56039187, 0.2540144 , 0.9349621 , 0.03424494]])